// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: proto/stego.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED          SessionState = 0
	SessionState_SESSION_STATE_PENDING_KEY_EXCHANGE SessionState = 1
	SessionState_SESSION_STATE_ACTIVE               SessionState = 2
	SessionState_SESSION_STATE_EXPIRED              SessionState = 3
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_PENDING_KEY_EXCHANGE",
		2: "SESSION_STATE_ACTIVE",
		3: "SESSION_STATE_EXPIRED",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED":          0,
		"SESSION_STATE_PENDING_KEY_EXCHANGE": 1,
		"SESSION_STATE_ACTIVE":               2,
		"SESSION_STATE_EXPIRED":              3,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stego_proto_enumTypes[0].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_proto_stego_proto_enumTypes[0]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{0}
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`                // Identifier for the other party
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // Human-readable name for the session
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_stego_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *CreateSessionRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_proto_stego_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_proto_stego_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{2}
}

func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSessionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_stego_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{3}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	State         SessionState           `protobuf:"varint,4,opt,name=state,proto3,enum=stego.v1.SessionState" json:"state,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_stego_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{4}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Session) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Session) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *Session) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Session) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type InitiateKeyExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateKeyExchangeRequest) Reset() {
	*x = InitiateKeyExchangeRequest{}
	mi := &file_proto_stego_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateKeyExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateKeyExchangeRequest) ProtoMessage() {}

func (x *InitiateKeyExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateKeyExchangeRequest.ProtoReflect.Descriptor instead.
func (*InitiateKeyExchangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{5}
}

func (x *InitiateKeyExchangeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type InitiateKeyExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // Our X25519 public key to share with peer
	KeyExchangeId string                 `protobuf:"bytes,2,opt,name=key_exchange_id,json=keyExchangeId,proto3" json:"key_exchange_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateKeyExchangeResponse) Reset() {
	*x = InitiateKeyExchangeResponse{}
	mi := &file_proto_stego_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateKeyExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateKeyExchangeResponse) ProtoMessage() {}

func (x *InitiateKeyExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateKeyExchangeResponse.ProtoReflect.Descriptor instead.
func (*InitiateKeyExchangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{6}
}

func (x *InitiateKeyExchangeResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *InitiateKeyExchangeResponse) GetKeyExchangeId() string {
	if x != nil {
		return x.KeyExchangeId
	}
	return ""
}

type CompleteKeyExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PeerPublicKey []byte                 `protobuf:"bytes,2,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"` // Peer's X25519 public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteKeyExchangeRequest) Reset() {
	*x = CompleteKeyExchangeRequest{}
	mi := &file_proto_stego_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteKeyExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteKeyExchangeRequest) ProtoMessage() {}

func (x *CompleteKeyExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteKeyExchangeRequest.ProtoReflect.Descriptor instead.
func (*CompleteKeyExchangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteKeyExchangeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompleteKeyExchangeRequest) GetPeerPublicKey() []byte {
	if x != nil {
		return x.PeerPublicKey
	}
	return nil
}

type CompleteKeyExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteKeyExchangeResponse) Reset() {
	*x = CompleteKeyExchangeResponse{}
	mi := &file_proto_stego_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteKeyExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteKeyExchangeResponse) ProtoMessage() {}

func (x *CompleteKeyExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteKeyExchangeResponse.ProtoReflect.Descriptor instead.
func (*CompleteKeyExchangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteKeyExchangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteKeyExchangeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type EncodeMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SecretMessage string                 `protobuf:"bytes,2,opt,name=secret_message,json=secretMessage,proto3" json:"secret_message,omitempty"` // Max ~30 chars recommended
	TopicHint     string                 `protobuf:"bytes,3,opt,name=topic_hint,json=topicHint,proto3" json:"topic_hint,omitempty"`             // User-provided cover topic
	DecoyMessage  string                 `protobuf:"bytes,4,opt,name=decoy_message,json=decoyMessage,proto3" json:"decoy_message,omitempty"`    // Optional: for deniability
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeMessageRequest) Reset() {
	*x = EncodeMessageRequest{}
	mi := &file_proto_stego_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeMessageRequest) ProtoMessage() {}

func (x *EncodeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeMessageRequest.ProtoReflect.Descriptor instead.
func (*EncodeMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{9}
}

func (x *EncodeMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EncodeMessageRequest) GetSecretMessage() string {
	if x != nil {
		return x.SecretMessage
	}
	return ""
}

func (x *EncodeMessageRequest) GetTopicHint() string {
	if x != nil {
		return x.TopicHint
	}
	return ""
}

func (x *EncodeMessageRequest) GetDecoyMessage() string {
	if x != nil {
		return x.DecoyMessage
	}
	return ""
}

type EncodeMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoverText     string                 `protobuf:"bytes,1,opt,name=cover_text,json=coverText,proto3" json:"cover_text,omitempty"` // Natural-looking text to send
	BitsEncoded   int32                  `protobuf:"varint,2,opt,name=bits_encoded,json=bitsEncoded,proto3" json:"bits_encoded,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeMessageResponse) Reset() {
	*x = EncodeMessageResponse{}
	mi := &file_proto_stego_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeMessageResponse) ProtoMessage() {}

func (x *EncodeMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeMessageResponse.ProtoReflect.Descriptor instead.
func (*EncodeMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{10}
}

func (x *EncodeMessageResponse) GetCoverText() string {
	if x != nil {
		return x.CoverText
	}
	return ""
}

func (x *EncodeMessageResponse) GetBitsEncoded() int32 {
	if x != nil {
		return x.BitsEncoded
	}
	return 0
}

func (x *EncodeMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type DecodeMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CoverText     string                 `protobuf:"bytes,2,opt,name=cover_text,json=coverText,proto3" json:"cover_text,omitempty"`
	DecoyKey      []byte                 `protobuf:"bytes,3,opt,name=decoy_key,json=decoyKey,proto3" json:"decoy_key,omitempty"`          // Optional: if using deniable decryption
	PeerReplies   []string               `protobuf:"bytes,4,rep,name=peer_replies,json=peerReplies,proto3" json:"peer_replies,omitempty"` // Optional: per-segment peer replies for interactive decode (segment2..N)
	TopicHint     string                 `protobuf:"bytes,5,opt,name=topic_hint,json=topicHint,proto3" json:"topic_hint,omitempty"`       // Optional: must match encode topic for reliable decode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeMessageRequest) Reset() {
	*x = DecodeMessageRequest{}
	mi := &file_proto_stego_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeMessageRequest) ProtoMessage() {}

func (x *DecodeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeMessageRequest.ProtoReflect.Descriptor instead.
func (*DecodeMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{11}
}

func (x *DecodeMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DecodeMessageRequest) GetCoverText() string {
	if x != nil {
		return x.CoverText
	}
	return ""
}

func (x *DecodeMessageRequest) GetDecoyKey() []byte {
	if x != nil {
		return x.DecoyKey
	}
	return nil
}

func (x *DecodeMessageRequest) GetPeerReplies() []string {
	if x != nil {
		return x.PeerReplies
	}
	return nil
}

func (x *DecodeMessageRequest) GetTopicHint() string {
	if x != nil {
		return x.TopicHint
	}
	return ""
}

type DecodeMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretMessage string                 `protobuf:"bytes,1,opt,name=secret_message,json=secretMessage,proto3" json:"secret_message,omitempty"`
	IsDecoy       bool                   `protobuf:"varint,2,opt,name=is_decoy,json=isDecoy,proto3" json:"is_decoy,omitempty"` // True if decoy key was used
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeMessageResponse) Reset() {
	*x = DecodeMessageResponse{}
	mi := &file_proto_stego_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeMessageResponse) ProtoMessage() {}

func (x *DecodeMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeMessageResponse.ProtoReflect.Descriptor instead.
func (*DecodeMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{12}
}

func (x *DecodeMessageResponse) GetSecretMessage() string {
	if x != nil {
		return x.SecretMessage
	}
	return ""
}

func (x *DecodeMessageResponse) GetIsDecoy() bool {
	if x != nil {
		return x.IsDecoy
	}
	return false
}

func (x *DecodeMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type StartInteractiveEncodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SecretMessage string                 `protobuf:"bytes,2,opt,name=secret_message,json=secretMessage,proto3" json:"secret_message,omitempty"`
	TopicHint     string                 `protobuf:"bytes,3,opt,name=topic_hint,json=topicHint,proto3" json:"topic_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInteractiveEncodeRequest) Reset() {
	*x = StartInteractiveEncodeRequest{}
	mi := &file_proto_stego_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInteractiveEncodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInteractiveEncodeRequest) ProtoMessage() {}

func (x *StartInteractiveEncodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInteractiveEncodeRequest.ProtoReflect.Descriptor instead.
func (*StartInteractiveEncodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{13}
}

func (x *StartInteractiveEncodeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartInteractiveEncodeRequest) GetSecretMessage() string {
	if x != nil {
		return x.SecretMessage
	}
	return ""
}

func (x *StartInteractiveEncodeRequest) GetTopicHint() string {
	if x != nil {
		return x.TopicHint
	}
	return ""
}

type StartInteractiveEncodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	CoverText     string                 `protobuf:"bytes,2,opt,name=cover_text,json=coverText,proto3" json:"cover_text,omitempty"`
	SegmentIndex  int32                  `protobuf:"varint,3,opt,name=segment_index,json=segmentIndex,proto3" json:"segment_index,omitempty"` // 1-based segment number just produced
	TotalSegments int32                  `protobuf:"varint,4,opt,name=total_segments,json=totalSegments,proto3" json:"total_segments,omitempty"`
	Done          bool                   `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"` // True when this was the final segment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInteractiveEncodeResponse) Reset() {
	*x = StartInteractiveEncodeResponse{}
	mi := &file_proto_stego_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInteractiveEncodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInteractiveEncodeResponse) ProtoMessage() {}

func (x *StartInteractiveEncodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInteractiveEncodeResponse.ProtoReflect.Descriptor instead.
func (*StartInteractiveEncodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{14}
}

func (x *StartInteractiveEncodeResponse) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *StartInteractiveEncodeResponse) GetCoverText() string {
	if x != nil {
		return x.CoverText
	}
	return ""
}

func (x *StartInteractiveEncodeResponse) GetSegmentIndex() int32 {
	if x != nil {
		return x.SegmentIndex
	}
	return 0
}

func (x *StartInteractiveEncodeResponse) GetTotalSegments() int32 {
	if x != nil {
		return x.TotalSegments
	}
	return 0
}

func (x *StartInteractiveEncodeResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type ContinueInteractiveEncodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	PeerReply     string                 `protobuf:"bytes,2,opt,name=peer_reply,json=peerReply,proto3" json:"peer_reply,omitempty"` // Plaintext reply from peer, used as context for next segment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueInteractiveEncodeRequest) Reset() {
	*x = ContinueInteractiveEncodeRequest{}
	mi := &file_proto_stego_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueInteractiveEncodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueInteractiveEncodeRequest) ProtoMessage() {}

func (x *ContinueInteractiveEncodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueInteractiveEncodeRequest.ProtoReflect.Descriptor instead.
func (*ContinueInteractiveEncodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{15}
}

func (x *ContinueInteractiveEncodeRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *ContinueInteractiveEncodeRequest) GetPeerReply() string {
	if x != nil {
		return x.PeerReply
	}
	return ""
}

type ContinueInteractiveEncodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	CoverText     string                 `protobuf:"bytes,2,opt,name=cover_text,json=coverText,proto3" json:"cover_text,omitempty"`
	SegmentIndex  int32                  `protobuf:"varint,3,opt,name=segment_index,json=segmentIndex,proto3" json:"segment_index,omitempty"` // 1-based segment number just produced
	TotalSegments int32                  `protobuf:"varint,4,opt,name=total_segments,json=totalSegments,proto3" json:"total_segments,omitempty"`
	Done          bool                   `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"` // True when this was the final segment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueInteractiveEncodeResponse) Reset() {
	*x = ContinueInteractiveEncodeResponse{}
	mi := &file_proto_stego_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueInteractiveEncodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueInteractiveEncodeResponse) ProtoMessage() {}

func (x *ContinueInteractiveEncodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueInteractiveEncodeResponse.ProtoReflect.Descriptor instead.
func (*ContinueInteractiveEncodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{16}
}

func (x *ContinueInteractiveEncodeResponse) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *ContinueInteractiveEncodeResponse) GetCoverText() string {
	if x != nil {
		return x.CoverText
	}
	return ""
}

func (x *ContinueInteractiveEncodeResponse) GetSegmentIndex() int32 {
	if x != nil {
		return x.SegmentIndex
	}
	return 0
}

func (x *ContinueInteractiveEncodeResponse) GetTotalSegments() int32 {
	if x != nil {
		return x.TotalSegments
	}
	return 0
}

func (x *ContinueInteractiveEncodeResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type GeneratePeerReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                      // The cover text just received
	TopicHint     string                 `protobuf:"bytes,2,opt,name=topic_hint,json=topicHint,proto3" json:"topic_hint,omitempty"` // Topic for contextual reply
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePeerReplyRequest) Reset() {
	*x = GeneratePeerReplyRequest{}
	mi := &file_proto_stego_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePeerReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePeerReplyRequest) ProtoMessage() {}

func (x *GeneratePeerReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePeerReplyRequest.ProtoReflect.Descriptor instead.
func (*GeneratePeerReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{17}
}

func (x *GeneratePeerReplyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GeneratePeerReplyRequest) GetTopicHint() string {
	if x != nil {
		return x.TopicHint
	}
	return ""
}

type GeneratePeerReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"` // Natural reply text (no hidden data)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePeerReplyResponse) Reset() {
	*x = GeneratePeerReplyResponse{}
	mi := &file_proto_stego_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePeerReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePeerReplyResponse) ProtoMessage() {}

func (x *GeneratePeerReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePeerReplyResponse.ProtoReflect.Descriptor instead.
func (*GeneratePeerReplyResponse) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{18}
}

func (x *GeneratePeerReplyResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type AddDecoyKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DecoyMessage  string                 `protobuf:"bytes,2,opt,name=decoy_message,json=decoyMessage,proto3" json:"decoy_message,omitempty"` // What this key should decrypt to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDecoyKeyRequest) Reset() {
	*x = AddDecoyKeyRequest{}
	mi := &file_proto_stego_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDecoyKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDecoyKeyRequest) ProtoMessage() {}

func (x *AddDecoyKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDecoyKeyRequest.ProtoReflect.Descriptor instead.
func (*AddDecoyKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{19}
}

func (x *AddDecoyKeyRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddDecoyKeyRequest) GetDecoyMessage() string {
	if x != nil {
		return x.DecoyMessage
	}
	return ""
}

type AddDecoyKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecoyKey      []byte                 `protobuf:"bytes,1,opt,name=decoy_key,json=decoyKey,proto3" json:"decoy_key,omitempty"` // Key that decrypts to a different message
	DecoyKeyId    string                 `protobuf:"bytes,2,opt,name=decoy_key_id,json=decoyKeyId,proto3" json:"decoy_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDecoyKeyResponse) Reset() {
	*x = AddDecoyKeyResponse{}
	mi := &file_proto_stego_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDecoyKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDecoyKeyResponse) ProtoMessage() {}

func (x *AddDecoyKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stego_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDecoyKeyResponse.ProtoReflect.Descriptor instead.
func (*AddDecoyKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_stego_proto_rawDescGZIP(), []int{20}
}

func (x *AddDecoyKeyResponse) GetDecoyKey() []byte {
	if x != nil {
		return x.DecoyKey
	}
	return nil
}

func (x *AddDecoyKeyResponse) GetDecoyKeyId() string {
	if x != nil {
		return x.DecoyKeyId
	}
	return ""
}

var File_proto_stego_proto protoreflect.FileDescriptor

const file_proto_stego_proto_rawDesc = "" +
	"\n" +
	"\x11proto/stego.proto\x12\bstego.v1\"R\n" +
	"\x14CreateSessionRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"C\n" +
	"\x13ListSessionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"[\n" +
	"\x14ListSessionsResponse\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.stego.v1.SessionR\bsessions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xc1\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12,\n" +
	"\x05state\x18\x04 \x01(\x0e2\x16.stego.v1.SessionStateR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\";\n" +
	"\x1aInitiateKeyExchangeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"d\n" +
	"\x1bInitiateKeyExchangeResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12&\n" +
	"\x0fkey_exchange_id\x18\x02 \x01(\tR\rkeyExchangeId\"c\n" +
	"\x1aCompleteKeyExchangeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12&\n" +
	"\x0fpeer_public_key\x18\x02 \x01(\fR\rpeerPublicKey\"\\\n" +
	"\x1bCompleteKeyExchangeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xa0\x01\n" +
	"\x14EncodeMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0esecret_message\x18\x02 \x01(\tR\rsecretMessage\x12\x1d\n" +
	"\n" +
	"topic_hint\x18\x03 \x01(\tR\ttopicHint\x12#\n" +
	"\rdecoy_message\x18\x04 \x01(\tR\fdecoyMessage\"x\n" +
	"\x15EncodeMessageResponse\x12\x1d\n" +
	"\n" +
	"cover_text\x18\x01 \x01(\tR\tcoverText\x12!\n" +
	"\fbits_encoded\x18\x02 \x01(\x05R\vbitsEncoded\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\"\xb3\x01\n" +
	"\x14DecodeMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"cover_text\x18\x02 \x01(\tR\tcoverText\x12\x1b\n" +
	"\tdecoy_key\x18\x03 \x01(\fR\bdecoyKey\x12!\n" +
	"\fpeer_replies\x18\x04 \x03(\tR\vpeerReplies\x12\x1d\n" +
	"\n" +
	"topic_hint\x18\x05 \x01(\tR\ttopicHint\"x\n" +
	"\x15DecodeMessageResponse\x12%\n" +
	"\x0esecret_message\x18\x01 \x01(\tR\rsecretMessage\x12\x19\n" +
	"\bis_decoy\x18\x02 \x01(\bR\aisDecoy\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\"\x84\x01\n" +
	"\x1dStartInteractiveEncodeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0esecret_message\x18\x02 \x01(\tR\rsecretMessage\x12\x1d\n" +
	"\n" +
	"topic_hint\x18\x03 \x01(\tR\ttopicHint\"\xb8\x01\n" +
	"\x1eStartInteractiveEncodeResponse\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x1d\n" +
	"\n" +
	"cover_text\x18\x02 \x01(\tR\tcoverText\x12#\n" +
	"\rsegment_index\x18\x03 \x01(\x05R\fsegmentIndex\x12%\n" +
	"\x0etotal_segments\x18\x04 \x01(\x05R\rtotalSegments\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\"Z\n" +
	" ContinueInteractiveEncodeRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x1d\n" +
	"\n" +
	"peer_reply\x18\x02 \x01(\tR\tpeerReply\"\xbb\x01\n" +
	"!ContinueInteractiveEncodeResponse\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x1d\n" +
	"\n" +
	"cover_text\x18\x02 \x01(\tR\tcoverText\x12#\n" +
	"\rsegment_index\x18\x03 \x01(\x05R\fsegmentIndex\x12%\n" +
	"\x0etotal_segments\x18\x04 \x01(\x05R\rtotalSegments\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\"S\n" +
	"\x18GeneratePeerReplyRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"topic_hint\x18\x02 \x01(\tR\ttopicHint\"1\n" +
	"\x19GeneratePeerReplyResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"X\n" +
	"\x12AddDecoyKeyRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rdecoy_message\x18\x02 \x01(\tR\fdecoyMessage\"T\n" +
	"\x13AddDecoyKeyResponse\x12\x1b\n" +
	"\tdecoy_key\x18\x01 \x01(\fR\bdecoyKey\x12 \n" +
	"\fdecoy_key_id\x18\x02 \x01(\tR\n" +
	"decoyKeyId*\x8a\x01\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"SESSION_STATE_PENDING_KEY_EXCHANGE\x10\x01\x12\x18\n" +
	"\x14SESSION_STATE_ACTIVE\x10\x02\x12\x19\n" +
	"\x15SESSION_STATE_EXPIRED\x10\x032\xd8\a\n" +
	"\fStegoService\x12B\n" +
	"\rCreateSession\x12\x1e.stego.v1.CreateSessionRequest\x1a\x11.stego.v1.Session\x12<\n" +
	"\n" +
	"GetSession\x12\x1b.stego.v1.GetSessionRequest\x1a\x11.stego.v1.Session\x12M\n" +
	"\fListSessions\x12\x1d.stego.v1.ListSessionsRequest\x1a\x1e.stego.v1.ListSessionsResponse\x12b\n" +
	"\x13InitiateKeyExchange\x12$.stego.v1.InitiateKeyExchangeRequest\x1a%.stego.v1.InitiateKeyExchangeResponse\x12b\n" +
	"\x13CompleteKeyExchange\x12$.stego.v1.CompleteKeyExchangeRequest\x1a%.stego.v1.CompleteKeyExchangeResponse\x12P\n" +
	"\rEncodeMessage\x12\x1e.stego.v1.EncodeMessageRequest\x1a\x1f.stego.v1.EncodeMessageResponse\x12P\n" +
	"\rDecodeMessage\x12\x1e.stego.v1.DecodeMessageRequest\x1a\x1f.stego.v1.DecodeMessageResponse\x12k\n" +
	"\x16StartInteractiveEncode\x12'.stego.v1.StartInteractiveEncodeRequest\x1a(.stego.v1.StartInteractiveEncodeResponse\x12t\n" +
	"\x19ContinueInteractiveEncode\x12*.stego.v1.ContinueInteractiveEncodeRequest\x1a+.stego.v1.ContinueInteractiveEncodeResponse\x12\\\n" +
	"\x11GeneratePeerReply\x12\".stego.v1.GeneratePeerReplyRequest\x1a#.stego.v1.GeneratePeerReplyResponse\x12J\n" +
	"\vAddDecoyKey\x12\x1c.stego.v1.AddDecoyKeyRequest\x1a\x1d.stego.v1.AddDecoyKeyResponseB\x1fZ\x1dgithub.com/cy/stegochat/protob\x06proto3"

var (
	file_proto_stego_proto_rawDescOnce sync.Once
	file_proto_stego_proto_rawDescData []byte
)

func file_proto_stego_proto_rawDescGZIP() []byte {
	file_proto_stego_proto_rawDescOnce.Do(func() {
		file_proto_stego_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stego_proto_rawDesc), len(file_proto_stego_proto_rawDesc)))
	})
	return file_proto_stego_proto_rawDescData
}

var file_proto_stego_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_stego_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_stego_proto_goTypes = []any{
	(SessionState)(0),                         // 0: stego.v1.SessionState
	(*CreateSessionRequest)(nil),              // 1: stego.v1.CreateSessionRequest
	(*GetSessionRequest)(nil),                 // 2: stego.v1.GetSessionRequest
	(*ListSessionsRequest)(nil),               // 3: stego.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),              // 4: stego.v1.ListSessionsResponse
	(*Session)(nil),                           // 5: stego.v1.Session
	(*InitiateKeyExchangeRequest)(nil),        // 6: stego.v1.InitiateKeyExchangeRequest
	(*InitiateKeyExchangeResponse)(nil),       // 7: stego.v1.InitiateKeyExchangeResponse
	(*CompleteKeyExchangeRequest)(nil),        // 8: stego.v1.CompleteKeyExchangeRequest
	(*CompleteKeyExchangeResponse)(nil),       // 9: stego.v1.CompleteKeyExchangeResponse
	(*EncodeMessageRequest)(nil),              // 10: stego.v1.EncodeMessageRequest
	(*EncodeMessageResponse)(nil),             // 11: stego.v1.EncodeMessageResponse
	(*DecodeMessageRequest)(nil),              // 12: stego.v1.DecodeMessageRequest
	(*DecodeMessageResponse)(nil),             // 13: stego.v1.DecodeMessageResponse
	(*StartInteractiveEncodeRequest)(nil),     // 14: stego.v1.StartInteractiveEncodeRequest
	(*StartInteractiveEncodeResponse)(nil),    // 15: stego.v1.StartInteractiveEncodeResponse
	(*ContinueInteractiveEncodeRequest)(nil),  // 16: stego.v1.ContinueInteractiveEncodeRequest
	(*ContinueInteractiveEncodeResponse)(nil), // 17: stego.v1.ContinueInteractiveEncodeResponse
	(*GeneratePeerReplyRequest)(nil),          // 18: stego.v1.GeneratePeerReplyRequest
	(*GeneratePeerReplyResponse)(nil),         // 19: stego.v1.GeneratePeerReplyResponse
	(*AddDecoyKeyRequest)(nil),                // 20: stego.v1.AddDecoyKeyRequest
	(*AddDecoyKeyResponse)(nil),               // 21: stego.v1.AddDecoyKeyResponse
}
var file_proto_stego_proto_depIdxs = []int32{
	5,  // 0: stego.v1.ListSessionsResponse.sessions:type_name -> stego.v1.Session
	0,  // 1: stego.v1.Session.state:type_name -> stego.v1.SessionState
	1,  // 2: stego.v1.StegoService.CreateSession:input_type -> stego.v1.CreateSessionRequest
	2,  // 3: stego.v1.StegoService.GetSession:input_type -> stego.v1.GetSessionRequest
	3,  // 4: stego.v1.StegoService.ListSessions:input_type -> stego.v1.ListSessionsRequest
	6,  // 5: stego.v1.StegoService.InitiateKeyExchange:input_type -> stego.v1.InitiateKeyExchangeRequest
	8,  // 6: stego.v1.StegoService.CompleteKeyExchange:input_type -> stego.v1.CompleteKeyExchangeRequest
	10, // 7: stego.v1.StegoService.EncodeMessage:input_type -> stego.v1.EncodeMessageRequest
	12, // 8: stego.v1.StegoService.DecodeMessage:input_type -> stego.v1.DecodeMessageRequest
	14, // 9: stego.v1.StegoService.StartInteractiveEncode:input_type -> stego.v1.StartInteractiveEncodeRequest
	16, // 10: stego.v1.StegoService.ContinueInteractiveEncode:input_type -> stego.v1.ContinueInteractiveEncodeRequest
	18, // 11: stego.v1.StegoService.GeneratePeerReply:input_type -> stego.v1.GeneratePeerReplyRequest
	20, // 12: stego.v1.StegoService.AddDecoyKey:input_type -> stego.v1.AddDecoyKeyRequest
	5,  // 13: stego.v1.StegoService.CreateSession:output_type -> stego.v1.Session
	5,  // 14: stego.v1.StegoService.GetSession:output_type -> stego.v1.Session
	4,  // 15: stego.v1.StegoService.ListSessions:output_type -> stego.v1.ListSessionsResponse
	7,  // 16: stego.v1.StegoService.InitiateKeyExchange:output_type -> stego.v1.InitiateKeyExchangeResponse
	9,  // 17: stego.v1.StegoService.CompleteKeyExchange:output_type -> stego.v1.CompleteKeyExchangeResponse
	11, // 18: stego.v1.StegoService.EncodeMessage:output_type -> stego.v1.EncodeMessageResponse
	13, // 19: stego.v1.StegoService.DecodeMessage:output_type -> stego.v1.DecodeMessageResponse
	15, // 20: stego.v1.StegoService.StartInteractiveEncode:output_type -> stego.v1.StartInteractiveEncodeResponse
	17, // 21: stego.v1.StegoService.ContinueInteractiveEncode:output_type -> stego.v1.ContinueInteractiveEncodeResponse
	19, // 22: stego.v1.StegoService.GeneratePeerReply:output_type -> stego.v1.GeneratePeerReplyResponse
	21, // 23: stego.v1.StegoService.AddDecoyKey:output_type -> stego.v1.AddDecoyKeyResponse
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_stego_proto_init() }
func file_proto_stego_proto_init() {
	if File_proto_stego_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stego_proto_rawDesc), len(file_proto_stego_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stego_proto_goTypes,
		DependencyIndexes: file_proto_stego_proto_depIdxs,
		EnumInfos:         file_proto_stego_proto_enumTypes,
		MessageInfos:      file_proto_stego_proto_msgTypes,
	}.Build()
	File_proto_stego_proto = out.File
	file_proto_stego_proto_goTypes = nil
	file_proto_stego_proto_depIdxs = nil
}
