// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.0
// source: proto/stego.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StegoService_CreateSession_FullMethodName             = "/stego.v1.StegoService/CreateSession"
	StegoService_GetSession_FullMethodName                = "/stego.v1.StegoService/GetSession"
	StegoService_ListSessions_FullMethodName              = "/stego.v1.StegoService/ListSessions"
	StegoService_InitiateKeyExchange_FullMethodName       = "/stego.v1.StegoService/InitiateKeyExchange"
	StegoService_CompleteKeyExchange_FullMethodName       = "/stego.v1.StegoService/CompleteKeyExchange"
	StegoService_EncodeMessage_FullMethodName             = "/stego.v1.StegoService/EncodeMessage"
	StegoService_DecodeMessage_FullMethodName             = "/stego.v1.StegoService/DecodeMessage"
	StegoService_StartInteractiveEncode_FullMethodName    = "/stego.v1.StegoService/StartInteractiveEncode"
	StegoService_ContinueInteractiveEncode_FullMethodName = "/stego.v1.StegoService/ContinueInteractiveEncode"
	StegoService_GeneratePeerReply_FullMethodName         = "/stego.v1.StegoService/GeneratePeerReply"
	StegoService_AddDecoyKey_FullMethodName               = "/stego.v1.StegoService/AddDecoyKey"
)

// StegoServiceClient is the client API for StegoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StegoService provides steganographic encoding/decoding capabilities
type StegoServiceClient interface {
	// Session management
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// Key exchange
	InitiateKeyExchange(ctx context.Context, in *InitiateKeyExchangeRequest, opts ...grpc.CallOption) (*InitiateKeyExchangeResponse, error)
	CompleteKeyExchange(ctx context.Context, in *CompleteKeyExchangeRequest, opts ...grpc.CallOption) (*CompleteKeyExchangeResponse, error)
	// Messaging
	EncodeMessage(ctx context.Context, in *EncodeMessageRequest, opts ...grpc.CallOption) (*EncodeMessageResponse, error)
	DecodeMessage(ctx context.Context, in *DecodeMessageRequest, opts ...grpc.CallOption) (*DecodeMessageResponse, error)
	StartInteractiveEncode(ctx context.Context, in *StartInteractiveEncodeRequest, opts ...grpc.CallOption) (*StartInteractiveEncodeResponse, error)
	ContinueInteractiveEncode(ctx context.Context, in *ContinueInteractiveEncodeRequest, opts ...grpc.CallOption) (*ContinueInteractiveEncodeResponse, error)
	// Peer reply generation (plain LLM text, no steganography)
	GeneratePeerReply(ctx context.Context, in *GeneratePeerReplyRequest, opts ...grpc.CallOption) (*GeneratePeerReplyResponse, error)
	// Deniability
	AddDecoyKey(ctx context.Context, in *AddDecoyKeyRequest, opts ...grpc.CallOption) (*AddDecoyKeyResponse, error)
}

type stegoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStegoServiceClient(cc grpc.ClientConnInterface) StegoServiceClient {
	return &stegoServiceClient{cc}
}

func (c *stegoServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, StegoService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stegoServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, StegoService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stegoServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, StegoService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stegoServiceClient) InitiateKeyExchange(ctx context.Context, in *InitiateKeyExchangeRequest, opts ...grpc.CallOption) (*InitiateKeyExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateKeyExchangeResponse)
	err := c.cc.Invoke(ctx, StegoService_InitiateKeyExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stegoServiceClient) CompleteKeyExchange(ctx context.Context, in *CompleteKeyExchangeRequest, opts ...grpc.CallOption) (*CompleteKeyExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteKeyExchangeResponse)
	err := c.cc.Invoke(ctx, StegoService_CompleteKeyExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stegoServiceClient) EncodeMessage(ctx context.Context, in *EncodeMessageRequest, opts ...grpc.CallOption) (*EncodeMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncodeMessageResponse)
	err := c.cc.Invoke(ctx, StegoService_EncodeMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stegoServiceClient) DecodeMessage(ctx context.Context, in *DecodeMessageRequest, opts ...grpc.CallOption) (*DecodeMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecodeMessageResponse)
	err := c.cc.Invoke(ctx, StegoService_DecodeMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stegoServiceClient) StartInteractiveEncode(ctx context.Context, in *StartInteractiveEncodeRequest, opts ...grpc.CallOption) (*StartInteractiveEncodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartInteractiveEncodeResponse)
	err := c.cc.Invoke(ctx, StegoService_StartInteractiveEncode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stegoServiceClient) ContinueInteractiveEncode(ctx context.Context, in *ContinueInteractiveEncodeRequest, opts ...grpc.CallOption) (*ContinueInteractiveEncodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContinueInteractiveEncodeResponse)
	err := c.cc.Invoke(ctx, StegoService_ContinueInteractiveEncode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stegoServiceClient) GeneratePeerReply(ctx context.Context, in *GeneratePeerReplyRequest, opts ...grpc.CallOption) (*GeneratePeerReplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratePeerReplyResponse)
	err := c.cc.Invoke(ctx, StegoService_GeneratePeerReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stegoServiceClient) AddDecoyKey(ctx context.Context, in *AddDecoyKeyRequest, opts ...grpc.CallOption) (*AddDecoyKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDecoyKeyResponse)
	err := c.cc.Invoke(ctx, StegoService_AddDecoyKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StegoServiceServer is the server API for StegoService service.
// All implementations must embed UnimplementedStegoServiceServer
// for forward compatibility.
//
// StegoService provides steganographic encoding/decoding capabilities
type StegoServiceServer interface {
	// Session management
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	GetSession(context.Context, *GetSessionRequest) (*Session, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// Key exchange
	InitiateKeyExchange(context.Context, *InitiateKeyExchangeRequest) (*InitiateKeyExchangeResponse, error)
	CompleteKeyExchange(context.Context, *CompleteKeyExchangeRequest) (*CompleteKeyExchangeResponse, error)
	// Messaging
	EncodeMessage(context.Context, *EncodeMessageRequest) (*EncodeMessageResponse, error)
	DecodeMessage(context.Context, *DecodeMessageRequest) (*DecodeMessageResponse, error)
	StartInteractiveEncode(context.Context, *StartInteractiveEncodeRequest) (*StartInteractiveEncodeResponse, error)
	ContinueInteractiveEncode(context.Context, *ContinueInteractiveEncodeRequest) (*ContinueInteractiveEncodeResponse, error)
	// Peer reply generation (plain LLM text, no steganography)
	GeneratePeerReply(context.Context, *GeneratePeerReplyRequest) (*GeneratePeerReplyResponse, error)
	// Deniability
	AddDecoyKey(context.Context, *AddDecoyKeyRequest) (*AddDecoyKeyResponse, error)
	mustEmbedUnimplementedStegoServiceServer()
}

// UnimplementedStegoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStegoServiceServer struct{}

func (UnimplementedStegoServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedStegoServiceServer) GetSession(context.Context, *GetSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedStegoServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedStegoServiceServer) InitiateKeyExchange(context.Context, *InitiateKeyExchangeRequest) (*InitiateKeyExchangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateKeyExchange not implemented")
}
func (UnimplementedStegoServiceServer) CompleteKeyExchange(context.Context, *CompleteKeyExchangeRequest) (*CompleteKeyExchangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteKeyExchange not implemented")
}
func (UnimplementedStegoServiceServer) EncodeMessage(context.Context, *EncodeMessageRequest) (*EncodeMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EncodeMessage not implemented")
}
func (UnimplementedStegoServiceServer) DecodeMessage(context.Context, *DecodeMessageRequest) (*DecodeMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecodeMessage not implemented")
}
func (UnimplementedStegoServiceServer) StartInteractiveEncode(context.Context, *StartInteractiveEncodeRequest) (*StartInteractiveEncodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInteractiveEncode not implemented")
}
func (UnimplementedStegoServiceServer) ContinueInteractiveEncode(context.Context, *ContinueInteractiveEncodeRequest) (*ContinueInteractiveEncodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContinueInteractiveEncode not implemented")
}
func (UnimplementedStegoServiceServer) GeneratePeerReply(context.Context, *GeneratePeerReplyRequest) (*GeneratePeerReplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePeerReply not implemented")
}
func (UnimplementedStegoServiceServer) AddDecoyKey(context.Context, *AddDecoyKeyRequest) (*AddDecoyKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDecoyKey not implemented")
}
func (UnimplementedStegoServiceServer) mustEmbedUnimplementedStegoServiceServer() {}
func (UnimplementedStegoServiceServer) testEmbeddedByValue()                      {}

// UnsafeStegoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StegoServiceServer will
// result in compilation errors.
type UnsafeStegoServiceServer interface {
	mustEmbedUnimplementedStegoServiceServer()
}

func RegisterStegoServiceServer(s grpc.ServiceRegistrar, srv StegoServiceServer) {
	// If the following call panics, it indicates UnimplementedStegoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StegoService_ServiceDesc, srv)
}

func _StegoService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StegoServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StegoService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StegoServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StegoService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StegoServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StegoService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StegoServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StegoService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StegoServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StegoService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StegoServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StegoService_InitiateKeyExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateKeyExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StegoServiceServer).InitiateKeyExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StegoService_InitiateKeyExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StegoServiceServer).InitiateKeyExchange(ctx, req.(*InitiateKeyExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StegoService_CompleteKeyExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteKeyExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StegoServiceServer).CompleteKeyExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StegoService_CompleteKeyExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StegoServiceServer).CompleteKeyExchange(ctx, req.(*CompleteKeyExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StegoService_EncodeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncodeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StegoServiceServer).EncodeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StegoService_EncodeMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StegoServiceServer).EncodeMessage(ctx, req.(*EncodeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StegoService_DecodeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StegoServiceServer).DecodeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StegoService_DecodeMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StegoServiceServer).DecodeMessage(ctx, req.(*DecodeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StegoService_StartInteractiveEncode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInteractiveEncodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StegoServiceServer).StartInteractiveEncode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StegoService_StartInteractiveEncode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StegoServiceServer).StartInteractiveEncode(ctx, req.(*StartInteractiveEncodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StegoService_ContinueInteractiveEncode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContinueInteractiveEncodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StegoServiceServer).ContinueInteractiveEncode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StegoService_ContinueInteractiveEncode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StegoServiceServer).ContinueInteractiveEncode(ctx, req.(*ContinueInteractiveEncodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StegoService_GeneratePeerReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePeerReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StegoServiceServer).GeneratePeerReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StegoService_GeneratePeerReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StegoServiceServer).GeneratePeerReply(ctx, req.(*GeneratePeerReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StegoService_AddDecoyKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDecoyKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StegoServiceServer).AddDecoyKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StegoService_AddDecoyKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StegoServiceServer).AddDecoyKey(ctx, req.(*AddDecoyKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StegoService_ServiceDesc is the grpc.ServiceDesc for StegoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StegoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stego.v1.StegoService",
	HandlerType: (*StegoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _StegoService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _StegoService_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _StegoService_ListSessions_Handler,
		},
		{
			MethodName: "InitiateKeyExchange",
			Handler:    _StegoService_InitiateKeyExchange_Handler,
		},
		{
			MethodName: "CompleteKeyExchange",
			Handler:    _StegoService_CompleteKeyExchange_Handler,
		},
		{
			MethodName: "EncodeMessage",
			Handler:    _StegoService_EncodeMessage_Handler,
		},
		{
			MethodName: "DecodeMessage",
			Handler:    _StegoService_DecodeMessage_Handler,
		},
		{
			MethodName: "StartInteractiveEncode",
			Handler:    _StegoService_StartInteractiveEncode_Handler,
		},
		{
			MethodName: "ContinueInteractiveEncode",
			Handler:    _StegoService_ContinueInteractiveEncode_Handler,
		},
		{
			MethodName: "GeneratePeerReply",
			Handler:    _StegoService_GeneratePeerReply_Handler,
		},
		{
			MethodName: "AddDecoyKey",
			Handler:    _StegoService_AddDecoyKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/stego.proto",
}
